CREATE TABLE IF NOT EXISTS personnel (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  tc_no VARCHAR(11) NOT NULL UNIQUE,
  address TEXT,
  phone VARCHAR(20),
  email VARCHAR(100),
  marital_status VARCHAR(20),
  criminal_record TEXT,
  children_count INT DEFAULT 0,
  driving_license VARCHAR(50),
  education_level VARCHAR(100),
  birth_date DATE,
  iban VARCHAR(34),
  department VARCHAR(100),
  certificates TEXT,
  size_pants VARCHAR(10),
  size_tshirt VARCHAR(10),
  size_coat VARCHAR(10),
  size_shoes VARCHAR(10),
  start_date DATE,
  end_date DATE,
  role VARCHAR(50) DEFAULT 'Araç Arkası',
  image_file VARCHAR(255),
  is_quitting BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
